### ISSUE TITLE
Highlighting already visited topics

### ISSUE THREAD

**Issue by NekitCorp** [phuoc-ng/this-vs-that#182]
It would be convenient if already visited topics were highlighted. Due to the release of new topics and just reading all the topics in a row, sometimes you start to get confused. As an example of implementation:

```css
a:visited > div {
  border-color: rgb(108, 92, 231);
}
```

![da5cd8a2766a98d30968c79dd457422a](https://user-images.githubusercontent.com/15874982/93592806-7d068000-f9bb-11ea-844e-2c451da8a69d.png)
